
#ifndef _HR_KRNLPROP_VERSION_H_
#define _HR_KRNLPROP_VERSION_H_

#define KRNLPROP_COPYRIGHT_YEARS "2011-2014"

#define KRNLPROP_V1 1
#define KRNLPROP_V2 0
#define KRNLPROP_V3 0
#define KRNLPROP_V4 0
#define KRNLPROP_VERSION  KRNLPROP_V1,KRNLPROP_V2,KRNLPROP_V3,KRNLPROP_V4

#define MK_VERSION_STR(V1, V2, V3, V4) #V1"."#V2"."#V3"."#V4

#define KRNLPROP_VERSION_STR MK_VERSION_STR(KRNLPROP_V1, KRNLPROP_V2, KRNLPROP_V3, KRNLPROP_V4)

#endif /* _HR_KRNLPROP_VERSION_H_ */
